version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing Maven
      - yum update -y
      - yum install -y maven
  pre_build:
    commands:
      - echo Pre-build phase started
      - echo Installing project dependencies
      - mvn clean install -DskipTests
  build:
    commands:
      - echo Build phase started
      - mvn package -DskipTests
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Post-build phase started
      - mv target/*.war $CODEBUILD_SRC_DIR # Replace with the actual path where you want to store the WAR file
 
artifacts:
  files:
    - $CODEBUILD_SRC_DIR/*.war # Replace with the actual path of the stored WAR file
 
cache:
  paths:
    - '/root/.m2/**/*'
