
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing Maven
      - yum update -y
      - yum install -y maven
  pre_build:
    commands:
      - echo Pre-build phase started
      - echo Installing project dependencies
      - mvn clean install -DskipTests
  build:
    commands:
      - echo Build phase started
      - mvn package -DskipTests
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Post-build phase started
      # Assuming the .war file is generated in the target directory.
      - mv target/*.war $CODEBUILD_SRC_DIR

artifacts:
  files:
    - target/*.war
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
