version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven 3.6.3
      - wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      - tar zxvf apache-maven-3.6.3-bin.tar.gz
      - export M2_HOME=$PWD/apache-maven-3.6.3
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -version
  pre_build:
    commands:
      - echo Pre-build phase started
      - mvn clean
  build:
    commands:
      - echo Build phase started
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Post-build phase started
      - |
        if ls target/my-warehouse-app-1.0.0.war 1> /dev/null 2>&1; then
          echo "WAR file found."
          mv target/my-warehouse-app-1.0.0.war target/ROOT.war
          mv target/ROOT.war  $CODEBUILD_SRC_DIR
        else
          echo "WAR file not found."
          exit 1
        fi

artifacts:
  files:
    - ROOT.war
  discard-paths: yes
  name: my-warehouse-app-$(date +%Y-%m-%d)

cache:
  paths:
    - '/root/.m2/**/*'
