
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing Maven 3.6.3
      - wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      - tar zxvf apache-maven-3.6.3-bin.tar.gz
      - export M2_HOME=$PWD/apache-maven-3.6.3
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -version # to check the correct version of Maven is installed
  pre_build:
    commands:
      - echo Pre-build phase started
      - echo Installing project dependencies
      - mvn clean install -DskipTests
  build:
    commands:
      - echo Build phase started
      - mvn package -DskipTests
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Post-build phase started
      # Assuming the .war file is generated in the target directory.
      - mv target/*.war $CODEBUILD_SRC_DIR

artifacts:
  files:
    - target/*.war
  discard-paths: yes
  name: backend-$(date +%Y-%m-%d)

cache:
  paths:
    - '/root/.m2/**/*'
